#!/usr/bin/env python3
"""Generate a per-waypoint ref_vel profile: fast on straights, braking into corners.

Run inside the dev image so ReferencePath builds the waypoints exactly as the MPC will, which
is what makes the emitted wp_id values line up.

Why per-waypoint. ref_vel.yaml ships ten coarse sections, and get_ref_vel just looks the waypoint
up in a sorted map -- no clamp, no limit on how many sections exist -- so one entry per waypoint
already works without touching any code. Ten sections cannot express a braking ramp: the whole
30 km/h section runs at 30 right up to the corner. That is why lifting the straights to 40 km/h
wholesale gave sixteen stalls and 355.9 s against the baseline's 287.5 s and one stall. The car
arrived at corner entry still carrying the speed, where the 0.2136 rad/s steering rate ceiling
cannot turn in time.

Corner speeds are pinned to what the car already does, not to grip. The shipped profile takes
corners at 22 km/h where |kappa| is about 0.17, a lateral demand near 6.4 m/s^2 -- far under the
20.09 m/s^2 the 36 s telemetry shows the vehicle holding. That gap is steering rate, not grip, so
corner speed is not for sale and --ay is calibrated to the shipped profile. Only straights rise.

    python3 tools/make_ref_vel.py --out ref_vel_perwp.yaml --v-max 40 --ay 6.5
"""
from __future__ import annotations

import argparse
import math
import pathlib

import numpy as np
import yaml
from ament_index_python.packages import get_package_share_directory

from multi_purpose_mpc_ros.common import convert_to_namedtuple
from multi_purpose_mpc_ros.core.map import Map
from multi_purpose_mpc_ros.core.reference_path import ReferencePath
from multi_purpose_mpc_ros.core.utils import load_ref_path


def build(kappa, ds, v_max, v_min, ay, a_max, a_min):
    """Curvature cap, then forward acceleration and backward braking passes, wrapped."""
    n = len(kappa)
    v = [min(v_max, max(v_min, math.sqrt(ay / max(abs(k), 1e-6)))) for k in kappa]
    for _ in range(2):                                  # closed circuit: converge the wrap
        for i in range(n):
            v[i] = min(v[i], math.sqrt(v[i - 1] ** 2 + 2 * a_max * ds[i - 1]))
        for i in range(n - 1, -1, -1):
            v[i] = min(v[i], math.sqrt(v[(i + 1) % n] ** 2 + 2 * abs(a_min) * ds[i]))
    return v


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="filename written into the config directory")
    ap.add_argument("--v-max", type=float, default=40.0, help="km/h ceiling on straights")
    ap.add_argument("--v-min", type=float, default=20.0, help="km/h floor")
    ap.add_argument("--ay", type=float, default=6.5, help="lateral budget, m/s^2")
    ap.add_argument("--a-max", type=float, default=1.35)
    ap.add_argument("--a-min", type=float, default=1.6)
    ap.add_argument("--step", type=float, default=0.5, help="round to this km/h step")
    args = ap.parse_args()

    pkg = pathlib.Path(get_package_share_directory("multi_purpose_mpc_ros"))
    cfg = convert_to_namedtuple(yaml.safe_load((pkg / "config/config.yaml").open()))
    m = Map(str(pkg / cfg.map.yaml_path))
    wx, wy, _, _ = load_ref_path(str(pkg / cfg.reference_path.csv_path))
    rp = ReferencePath(m, wx, wy, cfg.reference_path.resolution,
                       cfg.reference_path.smoothing_distance,
                       cfg.reference_path.max_width, cfg.reference_path.circular)
    W = rp.waypoints
    n = len(W)
    kappa = [abs(float(getattr(w, "kappa", 0.0))) for w in W]
    P = np.array([[w.x, w.y] for w in W])
    ds = [float(np.hypot(*(P[(i + 1) % n] - P[i]))) for i in range(n)]

    v = build(kappa, ds, args.v_max / 3.6, args.v_min / 3.6,
              args.ay, args.a_max, args.a_min)
    kmh = [round(vi * 3.6 / args.step) * args.step for vi in v]

    lap = sum(ds[i] / ((v[i] + v[(i + 1) % n]) / 2) for i in range(n))
    print(f"waypoints {n}  lap {lap:.2f} s  speed {min(kmh):.1f}-{max(kmh):.1f} km/h  "
          f"mean {sum(kmh)/n:.1f}")

    # Emit one section per waypoint. Adjacent duplicates are collapsed: get_ref_vel holds a
    # value until the next key, so repeating it changes nothing and only bloats the file.
    lines = ["# Generated by tools/make_ref_vel.py -- one section per waypoint.",
             f"# v_max {args.v_max} km/h, v_min {args.v_min}, ay {args.ay} m/s^2, "
             f"a_max {args.a_max}, a_min -{args.a_min}",
             f"# predicted lap {lap:.2f} s over {sum(ds):.1f} m",
             "ref_vel_configulator:"]
    prev = None
    kept = 0
    for i in range(n):
        if kmh[i] == prev:
            continue
        prev = kmh[i]
        kept += 1
        lines.append(f"  w{i:04d}:\n    ref_vel: {kmh[i]:.1f}\n    wp_id: {i}")
    out = pathlib.Path(get_package_share_directory("multi_purpose_mpc_ros")) / "config" / args.out
    # write to the source tree, which the share directory symlinks into
    src = pathlib.Path("/aichallenge/workspace/src/aichallenge_submit/multi_purpose_mpc_ros/config")
    (src / args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {src / args.out}  ({kept} sections after collapsing duplicates)")
    _ = out
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
